services:
  app:
    image: node:22-alpine
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn install && npx prisma migrate dev --name init && yarn run dev"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d portfolio"]
      interval: 10s
      timeout: 5s
      start_period: 10s

volumes:
  pgdata:
